title: stdout
url:  https://shimizu45.github.io/stdout
plugins:
  - jekyll-paginate
paginate: 10
paginate_path: /page-:num
source: .
destination: ./_site
sass:
    style: :compressed
    sass_dir: assets/css/
